### PR TITLE
Added 3Sum, also added question and input/output

### PR DESCRIPTION
**Pull request by rajatbh21**

### CODE REVIEW

**Comment by binsarjr** [comment]
please add descriptions and examples of input outputs of the problem

**Review by binsarjr — CHANGES_REQUESTED** [review]
please add descriptions and examples of input outputs of the problem

**Comment by rajatbh21** [comment]
Added the requested things

**Review by binsarjr — APPROVED** [review]
in future it is recommended to group by folder and also create questions and examples using markdown files. thank you for the contribution

**Pull request merged**
